-- Active: 1776057900509@@192.168.1.3@5432@ngrembel_asri
-- wahana   id, nama, slug, deskripsi, foto, harga_tiket, syarat, is_active, urutan
-- DROP TABLE IF EXISTS dashboard;
CREATE TABLE dashboard (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid (),
    slide_img_1 TEXT,
    slide_img_2 TEXT,
    slide_img_3 TEXT,
    slide_img_4 TEXT,
    slide_img_5 TEXT,
    tagline VARCHAR(255),
    quote_1 TEXT,
    stat_1_label VARCHAR(255),
    stat_1_value VARCHAR(10),
    stat_2_label VARCHAR(255),
    stat_2_value VARCHAR(10),
    stat_3_label VARCHAR(255),
    stat_3_value VARCHAR(10),
    stat_4_label VARCHAR(255),
    stat_4_value VARCHAR(10),
    sejarah_img_url TEXT,
    sejarah_tahun_berdiri VARCHAR(10),
    sejarah_title VARCHAR(255),
    sejarah_paragraf_1 TEXT,
    sejarah_paragraf_2 TEXT,
    sejarah_paragraf_3 TEXT,
    sejarah_year_1_lable VARCHAR(255),
    sejarah_year_1_value VARCHAR(255),
    sejarah_year_2_lable VARCHAR(255),
    sejarah_year_2_value VARCHAR(255),
    sejarah_year_3_lable VARCHAR(255),
    sejarah_year_3_value VARCHAR(255),
    sejarah_year_4_lable VARCHAR(255),
    sejarah_year_4_value VARCHAR(255),
    sejarah_year_5_lable VARCHAR(255),
    sejarah_year_5_value VARCHAR(255),
    tiket_deskripsi TEXT,
    tiket_weekday INTEGER,
    tiket_weekend INTEGER,
    jam_operasional VARCHAR(255),
    tagline_footer VARCHAR(255),
    alamat TEXT,
    telp VARCHAR(255),
    email VARCHAR(255),
    link_google_maps TEXT,
    link_facebook TEXT,
    link_instagram TEXT,
    link_youtube TEXT,
    link_tiktok TEXT,
    link_whatsapp TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by UUID REFERENCES "public"."members" (id),
    updated_by UUID REFERENCES "public"."members" (id)
);

INSERT INTO dashboard (
    slide_img_1,
    slide_img_2,
    slide_img_3,
    slide_img_4,
    slide_img_5,
    tagline,
    quote_1,
    stat_1_label,
    stat_1_value,
    stat_2_label,
    stat_2_value,
    stat_3_label,
    stat_3_value,
    stat_4_label,
    stat_4_value,
    sejarah_img_url,
    sejarah_tahun_berdiri,
    sejarah_title,
    sejarah_paragraf_1,
    sejarah_paragraf_2,
    sejarah_paragraf_3,
    sejarah_year_1_lable,
    sejarah_year_1_value,
    sejarah_year_2_lable,
    sejarah_year_2_value,
    sejarah_year_3_lable,
    sejarah_year_3_value,
    sejarah_year_4_lable,
    sejarah_year_4_value,
    sejarah_year_5_lable,
    sejarah_year_5_value,
    tiket_deskripsi,
    tiket_weekday,
    tiket_weekend,
    jam_operasional,
    tagline_footer,
    alamat,
    telp,
    email,
    link_google_maps,
    link_facebook,
    link_instagram,
    link_youtube,
    link_tiktok,
    link_whatsapp
) VALUES (
    '',
    '',
    '',
    '',
    '',
    'Wisata Termurah Sedunia',
    'Pelarian sempurna dari hiruk-pikuk kota — <br> alam hijau dan kenangan tak terlupakan.',
    'Hektar Lahan Hijau',
    '4',
    'Jenis Satwa',
    '50',
    'Tahun Berdiri',
    '25',
    'Ribu Pengunjung/Tahun',
    '260',
    '',
    '2001',
    'Perjalanan Lebih Dari Dua Dekade',
    'Wisata Ngrembel Asri lahir dari mimpi sederhana — menjaga kelestarian alam lokal sekaligus menciptakan ruang bermain yang edukatif. Berdiri di kaki perbukitan yang sejuk, wisata ini telah menjadi destinasi favorit keluarga Indonesia.',
    '',
    '',
    '2001 - Pendirian',
    'H. Zaenal membuka lahan 3 hektar sebagai kebun edukasi keluarga sederhana.',
    '2005 - Ekspansi',
    'Perluasan taman dan peluncuran mini zoo pertama dengan 12 jenis satwa lokal pilihan.',
    '2013 - Kebangkitan',
    'Re-opening taman dengan wahana permainan modern dan area kuliner.',
    '2020 - Transformasi',
    'Pengembangan area satwa liar dan fasilitas edukasi modern.',
    '2023 - Renovasi',
    'Renovasi total, field trip school program, dan koleksi satwa berkembang menjadi 50+ jenis.',
    'Tiket masuk sudah termasuk akses penuh ke semua area taman. <br/> Diskon khusus tersedia untuk rombongan, pelajar, dan lansia.',
    '5000',
    '9000',
    '08.00 - 17.00',
    'Wisata Ngrembel Asri — tempat keluarga menyatu dengan alam, merasakan ketenangan, dan menciptakan kenangan abadi.',
    'Jl. Raya Manyaran-Gunungpati KM 10 Semarang',
    '0857-4346-0206',
    '',
    '',
    'https://www.facebook.com/ngrembelasriofficial/',
    'https://www.instagram.com/ngrembelasriofficial/?igsh=MWwxM3U0NXh4ZXV6bg%3D%3D',
    'https://www.youtube.com/@WisataNgrembelAsri',
    'https://www.tiktok.com/@ngrembelasriofficial?_t=ZS-90kqpNZCsdE&_r=1',
    'https://wa.me/6285743460206'
);

SELECT * FROM dashboard;